In [ ]:
#importation numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [ ]:
#tableau scalaire

In [3]:
scalaire = np.array(5)
scalaire

array(5)

In [ ]:
#tableau a 1 dimension

In [4]:
vecteur = np.array([1,"a",3])
vecteur

array(['1', 'a', '3'], dtype='<U11')

In [5]:
type("a")

str

In [ ]:
#tableau a n dimension ou matrice

In [6]:
matrice = np.array([[1,2],[4,5],[7,8]])
matrice

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# Affichage avec print

In [19]:
print(scalaire)

5


In [20]:
print(vecteur)

['1' 'a' '3']


In [21]:
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#les dimensions 

In [22]:
scalaire.shape

()

In [23]:
vecteur.shape

(3,)

In [30]:
matrice.shape

(3, 2)

In [ ]:
#l'attribut shape

In [31]:
matrice.shape[0]

3

In [32]:
matrice.shape[1]

2

In [ ]:
#un vecteur avec une seule valeur

In [46]:
scalaire = np.array(0)
nbre_dim_1 = np.array([10])
print(scalaire)
print(nbre_dim_1[0])

0
10


In [ ]:
la difference entre un objet liste et un objet ndarray

In [49]:
liste = [1,2,3,4,5]
len(liste)

5

In [50]:
liste = [[1,2,3], [4,5,6]]
len (liste)

2

In [ ]:
#operateur somme +

In [ ]:
#somme liste

In [53]:
liste_1=[7,8,9]
liste_2=[1,2,3,4,5,6]
liste_2 + liste_1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#somme scalaire

In [9]:
scalaire_1 = np.array([2,3])
scalaire_2 = np.array(3)
scalaire_1 + scalaire_2

array([5, 6])

In [6]:
#somme vecteur

In [63]:
vecteur_1 = np.array([1,2,3])
vecteur_2 = np.array([2,8,7])
somme_vecteur = vecteur_1 + vecteur_2
print(vecteur_1, "+", vecteur_2, "=", somme_vecteur )

[1 2 3] + [2 8 7] = [ 3 10 10]


In [64]:
#somme matrice 
matrice_1 = np.array([[3,5,9],[2,5,8],[1,0,3]])
matrice_2 = np.array([[1,6,0],[1,7,2],[2,8,0]])
somme_matrice = matrice_1 + matrice_2
print(matrice_1)
print("+")
print(matrice_2)
print("=")
print(somme_matrice)

[[3 5 9]
 [2 5 8]
 [1 0 3]]
+
[[1 6 0]
 [1 7 2]
 [2 8 0]]
=
[[ 4 11  9]
 [ 3 12 10]
 [ 3  8  3]]


In [ ]:
#multiplication scalaire

In [4]:
scalaire = np.array(3)
scalaire * 2

6

In [ ]:
#multiplication vecteurs

In [7]:
vecteur = np.array([1,2,3])
vecteur_1= np.array([3,3,0])
vecteur * vecteur_1

array([3, 6, 0])

In [ ]:
#multiplication matrice

In [7]:
matrice_1= np.array([[1,2,3],[4,5,6]])
matrice_2= np.array([[9,3,1],[3,2,6]])
somme_matrice = matrice_1 * matrice_2
print(matrice_1)
print("fois")
print(matrice_2)
print("=")
print(somme_matrice)

[[1 2 3]
 [4 5 6]]
fois
[[9 3 1]
 [3 2 6]]
=
[[ 9  6  3]
 [12 10 36]]


In [ ]:
#la boucle 

In [11]:
nbre =([1,2,3])
[a*2 for a in nbre]

[2, 4, 6]

In [15]:
A_1=([2,4,8])
A_2=([4,6,7])
[An + Am for An,Am in zip(A_1,A_2)]

[6, 10, 15]

In [ ]:
#les fonctions

In [ ]:
#importation de logarithme népérien

In [ ]:
#fonctions avec une liste simple

In [9]:
from math import log
liste =[1,2,3,4]

In [ ]:
#fonction avec vecteur

In [66]:
vecteur=np.array([1,3,7])
np.log(vecteur)

array([0.        , 1.09861229, 1.94591015])

#fonctions avec la matrice

In [70]:
matrice = np.array([[2,3,5],[1,3,3],[25,36,81]])
np.sqrt(matrice)

array([[1.41421356, 1.73205081, 2.23606798],
       [1.        , 1.73205081, 1.73205081],
       [5.        , 6.        , 9.        ]])

In [ ]:
#exponentiel

In [64]:
vecteur = np.array([1,2,3])
np.exp(vecteur)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#la longeur

In [72]:
liste_des_listes =[1,3,3],[1,3,3,3],[1,4,8,9,7]
liste_des_listes

([1, 3, 3], [1, 3, 3, 3], [1, 4, 8, 9, 7])

In [ ]:
#matrice erreur

In [14]:
# matrice = np.array([2,3,2],[2,7,8])
# matrice

In [ ]:
#Quelque action avec np

In [15]:
An=[1,2,3]
Bn=["Ba","Bb","Bc"]
A= np.zeros(3,int)
print(A)
B=np.zeros_like(An)
print(B)
C=np.ones(4)
print(C)
D=np.ones_like(B)
print(D)
E=np.empty(3)
print(E)
F=np.empty_like(D)
print(F)
G=np.full(4,"Bil")
print(G)
H=np.full_like(Bn,An)
print(H)
a=np.max([1,2,5,2])
print (a)
b=np.min([1,2,5,2])
print(b)
c=np.sum([1,2,5,2])
print(c)
d=np.var([1,2,5,2])
print(d)
d=np.argmin([1,2,5,2])
print(d)
d=np.argmax([1,2,5,2])
print(d)
d=np.mean([1,2,5,2])
print(d)
d=np.std([1,2,5,2])
print(d)

[0 0 0]
[0 0 0]
[1. 1. 1. 1.]
[1 1 1]
[1.00994072e-311 0.00000000e+000 6.47591605e-319]
[-261605104        475          0]
['Bil' 'Bil' 'Bil' 'Bil']
['1' '2' '3']
5
1
10
2.25
0
2
2.5
1.5


In [11]:
E=np.array([1,2,3])
A=np.empty(E)
print(A)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.89143671e-307 6.23047503e-307 2.22526399e-307]]]


In [61]:
A=np.arange(4)
print(A)
B=np.arange(0,5)
print(B)
C=np.arange(0,10+1,2)
print(C)
D=np.linspace(0,5,5)
print(D)
E=np.linspace(0,1,2)
print(E)

[0 1 2 3]
[0 1 2 3 4]
[ 0  2  4  6  8 10]
[0.   1.25 2.5  3.75 5.  ]
[0. 1.]


In [ ]:
#dimension aléatoire

In [13]:
A=np.random.randint(0,10,4)
print(A)
B=np.random.rand(5)
print(B)
C=np.random.randn(4)
print(C)
D=np.random.uniform(1,10,3)
print(D)
E=np.random.normal(5,2,3)
print(E)

[9 0 3 6]
[0.7164632  0.19845414 0.73022862 0.38464761 0.0275951 ]
[1.38957266 0.80386922 0.4901907  0.03424971]
[8.56231595 9.85766279 1.41363388]
[4.53534187 2.96003304 5.94191737]


In [14]:
rang =np.random.default_rng()
rang.integers(0,10,3)
rang.random(3)
rang.standard_normal(4)

array([-0.36822882,  1.91795762,  0.12283327, -0.31164224])

In [16]:
#indexation 
a=np.arange(1,6)
a[2]
a[2:4]
b=a[-3:]
print(b)
a[::2]
a[[2,3,4]]
a[2:4] = 0
a[2:4] = 8
print (a)

[3 4 5]
[1 2 8 8 5]


In [63]:
#indexation complexe
a=np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])
A_1=np.any(a > 5)
A_2=np.all(a > 5)
print(A_1)
print(A_2)
#a=a[a>5]
#print(a)
#A_3=a[a>5]=8
#a[(a>=3)&(a<=5)]=0
b=np.nonzero(a>3)
print(b)
c=np.where(a>=5,1,0)
print(c)
d=np.clip(a,3,5)
print(d)

True
False
(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)
[0 0 0 0 1 1 1 1 1 0 0 0 0]
[3 3 3 4 5 5 5 5 5 4 3 3 3]
